# Generated by Django 5.2.16 on 2026-07-24 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero en el menú.', verbose_name='Orden en la carta')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('description', models.CharField(max_length=256, verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'El precio debe ser mayor que cero.')], verbose_name='Precio (CLP)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('disponible', models.BooleanField(default=True, help_text='Si se desmarca, el producto deja de ofrecerse al Cliente.', verbose_name='Disponible')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='menu.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria__orden', 'name'],
            },
        ),
    ]
